using Marathon.IO.Types.FileSystem;
using Marathon.Helpers;
using System;
using System.IO;
using System.IO.Compression;

namespace Marathon.Extensions
{
    public static class FileSystemExtensions
    {
        /// <summary>
        /// Exports a file.
        /// </summary>
        /// <typeparam name="T">The file type.</typeparam>
        /// <param name="in_file">The file to export.</param>
        /// <param name="in_path">The path on disk to export to.</param>
        public static void Export<T>(this IFile in_file, string in_path) where T : IFile, new()
        {
            if (string.IsNullOrEmpty(in_path))
                throw new ArgumentNullException(nameof(in_path));

            Directory.CreateDirectory(Path.GetDirectoryName(in_path));

            using (var fs = new FileStream(in_path, FileMode.Create))
                in_file.Open().CopyTo(fs);
        }

        /// <summary>
        /// Clones a file and returns a new instance of it with compressed data.
        /// </summary>
        /// <typeparam name="T">The file type.</typeparam>
        /// <param name="in_file">The file to compress.</param>
        /// <param name="in_compressionLevel">The level of compression to use.</param>
        /// <returns>A new file with compressed data.</returns>
        public static IFile Compress<T>(this IFile in_file, CompressionLevel in_compressionLevel = CompressionLevel.Optimal) where T : IFile, new()
        {
            if (in_file.CompressionService == null || in_file.UncompressedLength > 0)
                return in_file;

            var destStream = new MemoryStream();

            in_file.CompressionService.Compress(in_file.BaseStream, destStream, in_compressionLevel);

            var result = in_file.Clone();
            {
                result.UncompressedLength = in_file.BaseStream.Length;
                result.CompressionService = in_file.CompressionService;
                result.BaseStream = destStream;
            }

            return result;
        }

        /// <summary>
        /// Clones a file and returns a new instance of it with uncompressed data.
        /// </summary>
        /// <typeparam name="T">The file type.</typeparam>
        /// <param name="in_file">The file to decompress.</param>
        /// <returns>A new file with uncompressed data.</returns>
        public static IFile Decompress<T>(this IFile in_file) where T : IFile, new()
        {
            if (in_file.CompressionService == null || in_file.UncompressedLength <= 0)
                return in_file;

            var destStream = new MemoryStream();

            in_file.CompressionService.Decompress(in_file.Open(), destStream, in_file.UncompressedLength);

            var result = in_file.Clone();
            {
                result.UncompressedLength = 0;
                result.CompressionService = in_file.CompressionService;
                result.BaseStream = destStream;
            }

            return result;
        }

        /// <summary>
        /// Compares two file hashes generated by uncompressed data.
        /// </summary>
        /// <param name="in_left">The file to compare against.</param>
        /// <param name="in_right">The other file to check.</param>
        /// <returns><b>true</b> if the files are identical. Otherwise, <b>false</b>.</returns>
        public static bool Compare(this IFile in_left, IFile in_right)
        {
            var leftHash = HashHelper.ComputeStreamXxHash3(in_left.Decompress().Open());
            var rightHash = HashHelper.ComputeStreamXxHash3(in_right.Decompress().Open());

            return leftHash == rightHash;
        }
    }
}
