<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>13</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>2.0.0</Version>
    <Description>A library for SONIC THE HEDGEHOG (2006) file formats.</Description>
    <PackageProjectUrl>https://github.com/hyperbx/Marathon</PackageProjectUrl>
    <RepositoryUrl>https://github.com/hyperbx/Marathon</RepositoryUrl>
    <PackageTags>api;marathon;sonic-the-hedgehog;modding-tools;sonic-06;sonicnext</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>Marathon.png</PackageIcon>
    <PackageId>$(AssemblyName)</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Formats\Archive\**" />
    <Compile Remove="Formats\Audio\**" />
    <Compile Remove="Formats\Event\**" />
    <Compile Remove="Formats\Mesh\**" />
    <Compile Remove="Formats\Parameter\**" />
    <Compile Remove="Formats\Particle\**" />
    <Compile Remove="Formats\Placement\**" />
    <Compile Remove="Formats\Save\**" />
    <Compile Remove="Formats\Script\**" />
    <Compile Remove="Formats\Text\**" />
    <EmbeddedResource Remove="Formats\Archive\**" />
    <EmbeddedResource Remove="Formats\Audio\**" />
    <EmbeddedResource Remove="Formats\Event\**" />
    <EmbeddedResource Remove="Formats\Mesh\**" />
    <EmbeddedResource Remove="Formats\Parameter\**" />
    <EmbeddedResource Remove="Formats\Particle\**" />
    <EmbeddedResource Remove="Formats\Placement\**" />
    <EmbeddedResource Remove="Formats\Save\**" />
    <EmbeddedResource Remove="Formats\Script\**" />
    <EmbeddedResource Remove="Formats\Text\**" />
    <None Remove="Formats\Archive\**" />
    <None Remove="Formats\Audio\**" />
    <None Remove="Formats\Event\**" />
    <None Remove="Formats\Mesh\**" />
    <None Remove="Formats\Parameter\**" />
    <None Remove="Formats\Particle\**" />
    <None Remove="Formats\Placement\**" />
    <None Remove="Formats\Save\**" />
    <None Remove="Formats\Script\**" />
    <None Remove="Formats\Text\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Formats\Archive\ArcFile.cs" />
    <Compile Include="Formats\Audio\SoundBank.cs" />
    <Compile Include="Formats\Event\EventPlaybook.cs" />
    <Compile Include="Formats\Event\TimeEvent.cs" />
    <Compile Include="Formats\Mesh\LandCollision.cs" />
    <Compile Include="Formats\Mesh\ReflectionArea.cs" />
    <Compile Include="Formats\Mesh\SplinePathOld.cs" />
    <Compile Include="Formats\Mesh\SplinePath.cs" />
    <Compile Include="Formats\Parameter\EnemyParameterList.cs" />
    <Compile Include="Formats\Parameter\EnemyShotParameterList.cs" />
    <Compile Include="Formats\Parameter\ObjectExplosionParameterList.cs" />
    <Compile Include="Formats\Parameter\ObjectPhysicsParameterList.cs" />
    <Compile Include="Formats\Parameter\Package.cs" />
    <Compile Include="Formats\Parameter\PathObjParameterList.cs" />
    <Compile Include="Formats\Particle\ParticleContainer.cs" />
    <Compile Include="Formats\Particle\ParticleEffectBank.cs" />
    <Compile Include="Formats\Particle\ParticleGlobalSettings.cs" />
    <Compile Include="Formats\Particle\ParticleTextureBank.cs" />
    <Compile Include="Formats\Placement\PropLibrary.cs" />
    <Compile Include="Formats\Placement\StageSet.cs" />
    <Compile Include="Formats\Placement\StageSetDataType.cs" />
    <Compile Include="Formats\Placement\TemplateFactory.cs" />
    <Compile Include="Formats\Save\SaveEpisode.cs" />
    <Compile Include="Formats\Save\SaveFlags.cs" />
    <Compile Include="Formats\Save\SaveOptions.cs" />
    <Compile Include="Formats\Save\SaveRank.cs" />
    <Compile Include="Formats\Save\SaveData.cs" />
    <Compile Include="Formats\Save\SaveTrial.cs" />
    <Compile Include="Formats\Script\IndentationType.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\AlwaysLoop.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\Block.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\BooleanIndicator.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\Break.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\CompareBlock.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\DoEndBlock.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\ElseEndBlock.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\ForBlock.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\IfThenElseBlock.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\IfThenEndBlock.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\OuterBlock.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\RepeatBlock.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\SetBlock.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\TForBlock.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Blocks\WhileBlock.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Branches\AndBranch.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Branches\AssignNode.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Branches\Branch.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Branches\EQNode.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Branches\LENode.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Branches\LTNode.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Branches\NotBranch.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Branches\OrBranch.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Branches\TestNode.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Branches\TestSetNode.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Branches\TrueNode.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\CodeExtractor.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Code.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Constant.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Declaration.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Decompiler.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\Associativity.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\BinaryExpression.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\ClosureExpression.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\ConstantExpression.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\Expression.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\FunctionCall.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\GlobalExpression.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\LocalVariable.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\Precedence.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\TableEntry.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\TableLiteral.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\TableReference.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\UnaryExpression.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\UpvalueExpression.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Expressions\VariadicArgs.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Function.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\IOutputProvider.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Op.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Opcode.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\OpcodeFormat.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\OpcodeMap.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Operations\CallOperation.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Operations\GlobalSet.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Operations\Operation.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Operations\RegisterSet.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Operations\ReturnOperation.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Operations\TableSet.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Operations\UpvalueSet.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Output.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\OutputProviderStream.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\OutputProviderString.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Registers.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Statements\Assignment.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Statements\Declare.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Statements\FunctionCallStatement.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Statements\Return.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Statements\Statement.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Targets\GlobalTarget.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Targets\TableTarget.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Targets\Target.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Targets\UpvalueTarget.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Targets\VariableTarget.cs" />
    <Compile Include="Formats\Script\Lua\Decompiler\Upvalues.cs" />
    <Compile Include="Formats\Script\Lua\LuaBinary.cs" />
    <Compile Include="Formats\Script\Lua\Types\BHeader.cs" />
    <Compile Include="Formats\Script\Lua\Types\BInteger.cs" />
    <Compile Include="Formats\Script\Lua\Types\BIntegerType.cs" />
    <Compile Include="Formats\Script\Lua\Types\BList.cs" />
    <Compile Include="Formats\Script\Lua\Types\BObject.cs" />
    <Compile Include="Formats\Script\Lua\Types\BObjectType.cs" />
    <Compile Include="Formats\Script\Lua\Types\BSizeT.cs" />
    <Compile Include="Formats\Script\Lua\Types\BSizeTType.cs" />
    <Compile Include="Formats\Script\Lua\Types\LBoolean.cs" />
    <Compile Include="Formats\Script\Lua\Types\LBooleanType.cs" />
    <Compile Include="Formats\Script\Lua\Types\LConstantType.cs" />
    <Compile Include="Formats\Script\Lua\Types\LFunction.cs" />
    <Compile Include="Formats\Script\Lua\Types\LFunctionType.cs" />
    <Compile Include="Formats\Script\Lua\Types\LLocal.cs" />
    <Compile Include="Formats\Script\Lua\Types\LLocalType.cs" />
    <Compile Include="Formats\Script\Lua\Types\LNil.cs" />
    <Compile Include="Formats\Script\Lua\Types\LNumber.cs" />
    <Compile Include="Formats\Script\Lua\Types\LNumberType.cs" />
    <Compile Include="Formats\Script\Lua\Types\LObject.cs" />
    <Compile Include="Formats\Script\Lua\Types\LSourceLines.cs" />
    <Compile Include="Formats\Script\Lua\Types\LString.cs" />
    <Compile Include="Formats\Script\Lua\Types\LStringType.cs" />
    <Compile Include="Formats\Script\Lua\Types\LUpvalue.cs" />
    <Compile Include="Formats\Script\Lua\Types\LUpvalueType.cs" />
    <Compile Include="Formats\Text\TextBook.cs" />
    <Compile Include="Formats\Text\TextFontMap.cs" />
    <Compile Include="Formats\Text\TextFontPicture.cs" />
    <Compile Include="Formats\Text\TextFontProportion.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Marathon.Shared\Resources\Images\Logos\Marathon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Amicitia.IO" Version="1.2.1" />
    <PackageReference Include="AssimpNetter" Version="6.0.4" />
    <PackageReference Include="libHSON" Version="1.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="System.IO.Hashing" Version="11.0.0-preview.2.26159.112" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="11.0.0-preview.2.26159.112" />
    <PackageReference Include="UTF.Unknown" Version="2.6.0" />
  </ItemGroup>

  <Import Project="..\Marathon.Shared\Marathon.Shared.projitems" Label="Shared" />

</Project>
