//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathon.Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marathon.Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Marathon&gt;
        ///  &lt;!-- If no URL is specified, only your name will be displayed. --&gt;
        ///  &lt;Contributor URL=&quot;https://github.com/HyperPolygon64&quot;&gt;HyperPolygon64&lt;/Contributor&gt;
        ///  &lt;Contributor URL=&quot;https://github.com/Radfordhound&quot;&gt;Radfordhound&lt;/Contributor&gt;
        ///  &lt;Contributor URL=&quot;https://github.com/Knuxfan24&quot;&gt;Knuxfan24&lt;/Contributor&gt;
        ///  &lt;Contributor URL=&quot;https://github.com/GerbilSoft&quot;&gt;GerbilSoft&lt;/Contributor&gt;
        ///  &lt;Contributor URL=&quot;https://github.com/lllsondowlll&quot;&gt;Shadow LAG&lt;/Contri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is likely caused by a property in the configuration file that doesn&apos;t exist or it&apos;s being deserialised to an incorrect data type..
        /// </summary>
        internal static string Exception_InvalidSettingsException {
            get {
                return ResourceManager.GetString("Exception_InvalidSettingsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileDrop {
            get {
                object obj = ResourceManager.GetObject("FileDrop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Marathon&gt;
        ///  &lt;!-- If no extension is specified or is a duplicate, the entry will be disregarded. --&gt;
        ///  &lt;Type Extension=&quot;.*&quot;&gt;All files&lt;/Type&gt;
        ///  &lt;Type Extension=&quot;.pkg&quot;&gt;Asset Package&lt;/Type&gt;
        ///  &lt;Type Extension=&quot;.bin&quot;&gt;Collision&lt;/Type&gt;
        ///  &lt;Type Extension=&quot;.arc&quot;&gt;Compressed U8 Archive&lt;/Type&gt;
        ///  &lt;Type Extension=&quot;.dds&quot;&gt;DirectDraw Surface&lt;/Type&gt;
        ///  &lt;Type Extension=&quot;.path&quot;&gt;Path Spline&lt;/Type&gt;
        ///  &lt;Type Extension=&quot;.pft&quot;&gt;Picture Font&lt;/Type&gt;
        ///  &lt;Type Extension=&quot;.set&quot;&gt;Placement&lt;/Ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileTypes {
            get {
                return ResourceManager.GetString("FileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Main_Logo_Corner_Transparent {
            get {
                object obj = ResourceManager.GetObject("Main_Logo_Corner_Transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Main_Logo_Medium_Colour {
            get {
                object obj = ResourceManager.GetObject("Main_Logo_Medium_Colour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Main_Logo_Small_Dark {
            get {
                object obj = ResourceManager.GetObject("Main_Logo_Small_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Placeholder {
            get {
                object obj = ResourceManager.GetObject("Placeholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Marathon&gt;
        ///  &lt;!-- Vertex and Fragment shaders are inherited by name from .NET resources. --&gt;
        ///  &lt;Shader Vertex=&quot;SimpleVertex&quot; Fragment=&quot;SimpleFragment&quot;&gt;Simple&lt;/Shader&gt;
        ///&lt;/Marathon&gt;
        ///.
        /// </summary>
        internal static string Shaders {
            get {
                return ResourceManager.GetString("Shaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///in vec4 Colour;
        ///in vec2 Location;
        ///
        ///out vec4 FragmentColour;
        ///
        ///uniform sampler2D _Resource;
        ///
        ///void main()
        ///{
        ///	vec4 @texture = texture(_Resource, Location);
        ///
        ///	if (@texture.w &lt; 0.1)
        ///	{
        ///		discard;
        ///	}
        ///
        ///    FragmentColour = @texture * Colour;
        ///}.
        /// </summary>
        internal static string SimpleFragment {
            get {
                return ResourceManager.GetString("SimpleFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///layout (location = 0) in vec3 _Position;
        ///layout (location = 1) in vec3 _Normal;
        ///layout (location = 2) in vec4 _Colour;
        ///layout (location = 3) in vec2 _Location;
        ///
        ///uniform mat4 _Model;
        ///uniform mat4 _View;
        ///uniform mat4 _Projection;
        ///uniform vec4 _Highlight;
        ///
        ///out vec4 _OutputColour;
        ///out vec2 _OutputLocation;
        ///
        ///void main()
        ///{
        ///	gl_Position = _Projection * _View * _Model * vec4(_Position, 1.0);
        ///
        ///	_OutputColour = _Colour * _Highlight;
        ///    _OutputLocation = vec2(_Location.x, _Locat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleVertex {
            get {
                return ResourceManager.GetString("SimpleVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserControlForm_Close_Enabled {
            get {
                object obj = ResourceManager.GetObject("UserControlForm_Close_Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserControlForm_Maximise_Enabled {
            get {
                object obj = ResourceManager.GetObject("UserControlForm_Maximise_Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserControlForm_Minimise_Enabled {
            get {
                object obj = ResourceManager.GetObject("UserControlForm_Minimise_Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserControlForm_Restore_Enabled {
            get {
                object obj = ResourceManager.GetObject("UserControlForm_Restore_Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebBrowserExplorer_Back_Disabled {
            get {
                object obj = ResourceManager.GetObject("WebBrowserExplorer_Back_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebBrowserExplorer_Back_Enabled {
            get {
                object obj = ResourceManager.GetObject("WebBrowserExplorer_Back_Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebBrowserExplorer_Clipboard_Enabled {
            get {
                object obj = ResourceManager.GetObject("WebBrowserExplorer_Clipboard_Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebBrowserExplorer_DirectoryTree_Enabled {
            get {
                object obj = ResourceManager.GetObject("WebBrowserExplorer_DirectoryTree_Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebBrowserExplorer_Forward_Disabled {
            get {
                object obj = ResourceManager.GetObject("WebBrowserExplorer_Forward_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebBrowserExplorer_Forward_Enabled {
            get {
                object obj = ResourceManager.GetObject("WebBrowserExplorer_Forward_Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebBrowserExplorer_Up_Enabled {
            get {
                object obj = ResourceManager.GetObject("WebBrowserExplorer_Up_Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
