// NinjaNodeType.cs is licensed under the MIT License:
/* 
 * MIT License
 * 
 * Copyright (c) 2021 Knuxfan24
 * Copyright (c) 2021 Radfordhound
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

using System;

namespace Marathon.IO.Formats.Meshes.SegaNN
{
    // "Borrowed" from the Sonic 4 decomp.
    [Flags]
    public enum NinjaNodeType
    {
        NND_NODETYPE_UNIT_TRANSLATION = 1,
        NND_NODETYPE_UNIT_ROTATION = 2,
        NND_NODETYPE_UNIT_SCALING = 4,
        NND_NODETYPE_UNIT_INIT_MATRIX = 8,
        NND_NODETYPE_HIDE = 16,
        NND_NODETYPE_HIDE_BRANCH = 32,
        NND_NODETYPE_UNIT33_INIT_MATRIX = 64,
        NND_NODETYPE_ORTHO33_INIT_MATRIX = 128,
        NND_NODETYPE_ROTATE_TYPE_XYZ = 0,
        NND_NODETYPE_ROTATE_TYPE_XZY = 256,
        NND_NODETYPE_ROTATE_TYPE_YXZ = 512,
        NND_NODETYPE_ROTATE_TYPE_YZX = 768,
        NND_NODETYPE_ROTATE_TYPE_ZXY = 1024,
        NND_NODETYPE_ROTATE_TYPE_ZYX = 1280,
        NND_NODETYPE_ROTATE_TYPE_XYX = 1536,
        NND_NODETYPE_ROTATE_TYPE_XZX = 1792,
        NND_NODETYPE_ROTATE_TYPE_YXY = 2048,
        NND_NODETYPE_ROTATE_TYPE_YZY = 2304,
        NND_NODETYPE_ROTATE_TYPE_ZXZ = 2560,
        NND_NODETYPE_ROTATE_TYPE_ZYZ = 2816,
        NND_NODETYPE_ROTATE_TYPE_MASK = 3840,
        NND_NODETYPE_INHERIT_ONLY_TRANSLATION = 4096,
        NND_NODETYPE_SIIK_EFFECTOR = 8192,
        NND_NODETYPE_SIIK_1BONE_IK_JOINT1 = 16384,
        NND_NODETYPE_SIIK_2BONE_IK_JOINT1 = 32768,
        NND_NODETYPE_SIIK_2BONE_IK_JOINT2 = 65536,
        NND_NODETYPE_SIIK_MINUS_PREFROT_Z = 131072,
        NND_NODETYPE_1BONE_IK_CHAIN_ROOT = 33554432,
        NND_NODETYPE_2BONE_IK_CHAIN_ROOT = 67108864,
        NND_NODETYPE_IK_EFFECTOR = 8192,
        NND_NODETYPE_1BONE_IK_JOINT1 = 16384,
        NND_NODETYPE_2BONE_IK_JOINT1 = 32768,
        NND_NODETYPE_2BONE_IK_JOINT2 = 65536,
        NND_NODETYPE_IK_MINUS_PREFROT_Z = 131072,
        NND_NODETYPE_XSIIK = 134217728,
        NND_NODETYPE_XSIIK_1BONE_IK_CHAIN_ROOT = 167772160,
        NND_NODETYPE_XSIIK_2BONE_IK_CHAIN_ROOT = 201326592,
        NND_NODETYPE_XSIIK_EFFECTOR = 134225920,
        NND_NODETYPE_XSIIK_1BONE_IK_JOINT1 = 134234112,
        NND_NODETYPE_XSIIK_2BONE_IK_JOINT1 = 134250496,
        NND_NODETYPE_XSIIK_2BONE_IK_JOINT2 = 134283264,
        NND_NODETYPE_XSIIK_MINUS_PREFROT_Z = 134348800,
        NND_NODETYPE_IK_MASK = 235134976,
        NND_NODETYPE_RESET_SCALING_X = 262144,
        NND_NODETYPE_RESET_SCALING_Y = 524288,
        NND_NODETYPE_RESET_SCALING_Z = 1048576,
        NND_NODETYPE_BBOX_DATA = 2097152,
        NND_NODETYPE_BBOX_PRIOR_SPHERE = 4194304,
        NND_NODETYPE_BBOX_DOMINATE_X = 8388608,
        NND_NODETYPE_BBOX_DOMINATE_Y = 16777216,
        NND_NODETYPE_BBOX_DOMINATE_Z = 25165824,
        NND_NODETYPE_BBOX_DOMINATE_MASK = 25165824
    }
}
