using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;

namespace Marathon.Formats.Ninja.Flags
{
    [Flags]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SubMotionType : uint
    {
        // Masks
        NND_SMOTTYPE_FRAME_MASK = 3,
        NND_SMOTTYPE_ANGLE_MASK = 28,
        NND_SMOTTYPE_TRANSLATION_MASK = 0x700U,
        NND_SMOTTYPE_DIFFUSE_MASK = 0xE00U,
        NND_SMOTTYPE_ROTATION_MASK = 0x7800U,
        NND_SMOTTYPE_SPECULAR_MASK = 0xE000U,
        NND_SMOTTYPE_SCALING_MASK = 0x38000U,
        NND_SMOTTYPE_USER_MASK = 0xC0000U,
        NND_SMOTTYPE_LIGHT_COLOR_MASK = 0xE00000U,
        NND_SMOTTYPE_OFFSET_MASK = 0x1800000U,
        NND_SMOTTYPE_TARGET_MASK = 0x1C0000U,
        NND_SMOTTYPE_AMBIENT_MASK = 0x1C0000U,
        NND_SMOTTYPE_UPTARGET_MASK = 0x1C00000U,
        NND_SMOTTYPE_TEXTURE_MASK = 0x1E00000U,
        NND_SMOTTYPE_UPVECTOR_MASK = 0xE000000U,
        NND_SMOTTYPE_VALUETYPE_MASK = 0xFFFFFF00U,

        // Frame types
        NND_SMOTTYPE_FRAME_FLOAT = 1,
        NND_SMOTTYPE_FRAME_SINT16 = 2,

        // Angle types
        NND_SMOTTYPE_ANGLE_RADIAN = 4,
        NND_SMOTTYPE_ANGLE_ANGLE32 = 8,
        NND_SMOTTYPE_ANGLE_ANGLE16 = 16,

        // Node types
        NND_SMOTTYPE_TRANSLATION_X = 0x100U,
        NND_SMOTTYPE_TRANSLATION_Y = 0x200U,
        NND_SMOTTYPE_TRANSLATION_Z = 0x400U,
        NND_SMOTTYPE_TRANSLATION_XYZ = NND_SMOTTYPE_TRANSLATION_X | NND_SMOTTYPE_TRANSLATION_Y | NND_SMOTTYPE_TRANSLATION_Z,
        NND_SMOTTYPE_ROTATION_X = 0x800U,
        NND_SMOTTYPE_ROTATION_Y = 0x1000U,
        NND_SMOTTYPE_ROTATION_Z = 0x2000U,
        NND_SMOTTYPE_ROTATION_XYZ = NND_SMOTTYPE_ROTATION_X | NND_SMOTTYPE_ROTATION_Y | NND_SMOTTYPE_ROTATION_Z,
        NND_SMOTTYPE_QUATERNION = 0x4000U,
        NND_SMOTTYPE_SCALING_X = 0x8000U,
        NND_SMOTTYPE_SCALING_Y = 0x10000U,
        NND_SMOTTYPE_SCALING_Z = 0x20000U,
        NND_SMOTTYPE_SCALING_XYZ = NND_SMOTTYPE_SCALING_X | NND_SMOTTYPE_SCALING_Y | NND_SMOTTYPE_SCALING_Z,
        NND_SMOTTYPE_USER_UINT32 = 0x40000U,
        NND_SMOTTYPE_USER_FLOAT = 0x80000U,
        NND_SMOTTYPE_NODEHIDE = 0x100000U,

        // Camera types
        NND_SMOTTYPE_TARGET_X = 0x40000U,
        NND_SMOTTYPE_TARGET_Y = 0x80000U,
        NND_SMOTTYPE_TARGET_Z = 0x100000U,
        NND_SMOTTYPE_TARGET_XYZ = NND_SMOTTYPE_TARGET_X | NND_SMOTTYPE_TARGET_Y | NND_SMOTTYPE_TARGET_Z,
        NND_SMOTTYPE_ROLL = 0x200000U,
        NND_SMOTTYPE_UPTARGET_X = 0x400000U,
        NND_SMOTTYPE_UPTARGET_Y = 0x800000U,
        NND_SMOTTYPE_UPTARGET_Z = 0x1000000U,
        NND_SMOTTYPE_UPTARGET_XYZ = NND_SMOTTYPE_UPTARGET_X | NND_SMOTTYPE_UPTARGET_Y | NND_SMOTTYPE_UPTARGET_Z,
        NND_SMOTTYPE_UPVECTOR_X = 0x2000000U,
        NND_SMOTTYPE_UPVECTOR_Y = 0x4000000U,
        NND_SMOTTYPE_UPVECTOR_Z = 0x8000000U,
        NND_SMOTTYPE_UPVECTOR_XYZ = NND_SMOTTYPE_UPVECTOR_X | NND_SMOTTYPE_UPVECTOR_Y | NND_SMOTTYPE_UPVECTOR_Z,
        NND_SMOTTYPE_FOVY = 0x10000000U,
        NND_SMOTTYPE_ZNEAR = 0x20000000U,
        NND_SMOTTYPE_ZFAR = 0x40000000U,
        NND_SMOTTYPE_ASPECT = 0x80000000U,

        // Light types
        NND_SMOTTYPE_LIGHT_COLOR_R = 0x200000U,
        NND_SMOTTYPE_LIGHT_COLOR_G = 0x400000U,
        NND_SMOTTYPE_LIGHT_COLOR_B = 0x800000U,
        NND_SMOTTYPE_LIGHT_COLOR_RGB = NND_SMOTTYPE_LIGHT_COLOR_R | NND_SMOTTYPE_LIGHT_COLOR_G | NND_SMOTTYPE_LIGHT_COLOR_B,
        NND_SMOTTYPE_LIGHT_ALPHA = 0x1000000U,
        NND_SMOTTYPE_LIGHT_INTENSITY = 0x2000000U,
        NND_SMOTTYPE_FALLOFF_START = 0x4000000U,
        NND_SMOTTYPE_FALLOFF_END = 0x8000000U,
        NND_SMOTTYPE_INNER_ANGLE = 0x10000000U,
        NND_SMOTTYPE_OUTER_ANGLE = 0x20000000U,
        NND_SMOTTYPE_INNER_RANGE = 0x40000000U,
        NND_SMOTTYPE_OUTER_RANGE = 0x80000000U,

        // Morph types
        NND_SMOTTYPE_MORPH_WEIGHT = 0x1000000U,

        // Material types
        NND_SMOTTYPE_HIDE = 0x100U,
        NND_SMOTTYPE_DIFFUSE_R = 0x200U,
        NND_SMOTTYPE_DIFFUSE_G = 0x400U,
        NND_SMOTTYPE_DIFFUSE_B = 0x800U,
        NND_SMOTTYPE_DIFFUSE_RGB = NND_SMOTTYPE_DIFFUSE_R | NND_SMOTTYPE_DIFFUSE_G | NND_SMOTTYPE_DIFFUSE_B,
        NND_SMOTTYPE_ALPHA = 0x1000U,
        NND_SMOTTYPE_SPECULAR_R = 0x2000U,
        NND_SMOTTYPE_SPECULAR_G = 0x4000U,
        NND_SMOTTYPE_SPECULAR_B = 0x8000U,
        NND_SMOTTYPE_SPECULAR_RGB = NND_SMOTTYPE_SPECULAR_R | NND_SMOTTYPE_SPECULAR_G | NND_SMOTTYPE_SPECULAR_B,
        NND_SMOTTYPE_SPECULAR_LEVEL = 0x10000U,
        NND_SMOTTYPE_SPECULAR_GLOSS = 0x20000U,
        NND_SMOTTYPE_AMBIENT_R = 0x40000U,
        NND_SMOTTYPE_AMBIENT_G = 0x80000U,
        NND_SMOTTYPE_AMBIENT_B = 0x100000U,
        NND_SMOTTYPE_AMBIENT_RGB = NND_SMOTTYPE_AMBIENT_R | NND_SMOTTYPE_AMBIENT_G | NND_SMOTTYPE_AMBIENT_B,
        NND_SMOTTYPE_TEXTURE_INDEX = 0x200000U,
        NND_SMOTTYPE_TEXTURE_BLEND = 0x400000U,
        NND_SMOTTYPE_OFFSET_U = 0x800000U,
        NND_SMOTTYPE_OFFSET_V = 0x1000000U,
        NND_SMOTTYPE_OFFSET_UV = NND_SMOTTYPE_OFFSET_U | NND_SMOTTYPE_OFFSET_V,
        NND_SMOTTYPE_MATCLBK_USER = 0x2000000U
    }
}
