using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;

namespace Marathon.Formats.Ninja.Flags
{
    [Flags]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VertexFormat : uint
    {
        // Xbox types
        NND_VTXTYPE_XB_POSITION = 0x01U,
        NND_VTXTYPE_XB_NORMAL = 0x02U,
        NND_VTXTYPE_XB_COLOR = 0x08U,
        NND_VTXTYPE_XB_COLOR2 = 0x10U,
        NND_VTXTYPE_XB_TANGENT = 0x40U,   // TODO: might be 0x100?
        NND_VTXTYPE_XB_BINORMAL = 0x100U, // TODO: might be 0x40?
        NND_VTXTYPE_XB_MTX_INDEX4 = 0x400U,
        NND_VTXTYPE_XB_WEIGHT3 = 0x7000U,
        NND_VTXTYPE_XB_SINGLETEXCOORD = 0x10000U,
        NND_VTXTYPE_XB_DOUBLETEXCOORD = 0x20000U,
        NND_VTXTYPE_XB_PNCT = NND_VTXTYPE_XB_POSITION | NND_VTXTYPE_XB_NORMAL | NND_VTXTYPE_XB_COLOR | NND_VTXTYPE_XB_SINGLETEXCOORD,
        NND_VTXTYPE_XB_PW4INCT = NND_VTXTYPE_XB_POSITION | NND_VTXTYPE_XB_WEIGHT3 | NND_VTXTYPE_XB_MTX_INDEX4 | NND_VTXTYPE_XB_NORMAL | NND_VTXTYPE_XB_COLOR | NND_VTXTYPE_XB_SINGLETEXCOORD,
        NND_VTXTYPE_XB_PW4INCTAB = NND_VTXTYPE_XB_POSITION | NND_VTXTYPE_XB_WEIGHT3 | NND_VTXTYPE_XB_MTX_INDEX4 | NND_VTXTYPE_XB_NORMAL | NND_VTXTYPE_XB_COLOR | NND_VTXTYPE_XB_SINGLETEXCOORD | NND_VTXTYPE_XB_TANGENT | NND_VTXTYPE_XB_BINORMAL
    }
}
