//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap adxBG {
            get {
                object obj = ResourceManager.GetObject("adxBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon adxIcon {
            get {
                object obj = ResourceManager.GetObject("adxIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap adxLogo {
            get {
                object obj = ResourceManager.GetObject("adxLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] arctool {
            get {
                object obj = ResourceManager.GetObject("arctool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap at3BG {
            get {
                object obj = ResourceManager.GetObject("at3BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon at3Icon {
            get {
                object obj = ResourceManager.GetObject("at3Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap at3Logo {
            get {
                object obj = ResourceManager.GetObject("at3Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_volume_high {
            get {
                object obj = ResourceManager.GetObject("audio_volume_high", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_volume_low {
            get {
                object obj = ResourceManager.GetObject("audio_volume_low", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_volume_medium {
            get {
                object obj = ResourceManager.GetObject("audio_volume_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_volume_mute {
            get {
                object obj = ResourceManager.GetObject("audio_volume_mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_volume_none {
            get {
                object obj = ResourceManager.GetObject("audio_volume_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap csbBG {
            get {
                object obj = ResourceManager.GetObject("csbBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon csbIcon {
            get {
                object obj = ResourceManager.GetObject("csbIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap csbLogo {
            get {
                object obj = ResourceManager.GetObject("csbLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38A0008D503AD8B891253BCDFD9608B2.
        /// </summary>
        internal static string hash_arctool {
            get {
                return ResourceManager.GetString("hash_arctool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E3A802A193FDDEFA2556761A717E3BC3.
        /// </summary>
        internal static string hash_at3tool {
            get {
                return ResourceManager.GetString("hash_at3tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5E7127420FFE9FC418CE43F7280C918D.
        /// </summary>
        internal static string hash_luac50 {
            get {
                return ResourceManager.GetString("hash_luac50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7614FC8E0ED2DB168C93B69887513FCB.
        /// </summary>
        internal static string hash_mst06 {
            get {
                return ResourceManager.GetString("hash_mst06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 122E997019F43E1F54370313F358D50F.
        /// </summary>
        internal static string hash_repack {
            get {
                return ResourceManager.GetString("hash_repack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 062AC6249016BDD62126EF6ADF89754D.
        /// </summary>
        internal static string hash_s06col {
            get {
                return ResourceManager.GetString("hash_s06col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C6D5D656CB56E3FC1C7ACD47DC07280B.
        /// </summary>
        internal static string hash_s06collision {
            get {
                return ResourceManager.GetString("hash_s06collision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 169714A7FF4D68818EF1F8298737838C.
        /// </summary>
        internal static string hash_texconv {
            get {
                return ResourceManager.GetString("hash_texconv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0CBFE82554E6405F0B7C6D116126A100.
        /// </summary>
        internal static string hash_towav {
            get {
                return ResourceManager.GetString("hash_towav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEBB0AC6785DDC775C5CE99D4A614FC5.
        /// </summary>
        internal static string hash_unlub {
            get {
                return ResourceManager.GetString("hash_unlub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC37178A363E57BC46E81F7857541F9A.
        /// </summary>
        internal static string hash_unpack {
            get {
                return ResourceManager.GetString("hash_unpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1924FA8082EFB8DF878BA9454698D85.
        /// </summary>
        internal static string hash_xextool {
            get {
                return ResourceManager.GetString("hash_xextool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8DC5FB8541250E0D50FEED5EB36E4F23.
        /// </summary>
        internal static string hash_xmaencode {
            get {
                return ResourceManager.GetString("hash_xmaencode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6771D7D3C44B79919C4D3F8731B758E5.
        /// </summary>
        internal static string hash_xno2dae {
            get {
                return ResourceManager.GetString("hash_xno2dae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HedgeLib {
            get {
                object obj = ResourceManager.GetObject("HedgeLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_exception {
            get {
                object obj = ResourceManager.GetObject("logo_exception", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_main {
            get {
                object obj = ResourceManager.GetObject("logo_main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon logo_main_icon {
            get {
                object obj = ResourceManager.GetObject("logo_main_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lua50 {
            get {
                object obj = ResourceManager.GetObject("lua50", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] luac50 {
            get {
                object obj = ResourceManager.GetObject("luac50", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mst06 {
            get {
                object obj = ResourceManager.GetObject("mst06", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ookii_Dialogs {
            get {
                object obj = ResourceManager.GetObject("Ookii_Dialogs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PS3_at3tool {
            get {
                object obj = ResourceManager.GetObject("PS3_at3tool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] repack {
            get {
                object obj = ResourceManager.GetObject("repack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] s06col {
            get {
                object obj = ResourceManager.GetObject("s06col", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] s06collision {
            get {
                object obj = ResourceManager.GetObject("s06collision", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SonicAudioLib {
            get {
                object obj = ResourceManager.GetObject("SonicAudioLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] texconv {
            get {
                object obj = ResourceManager.GetObject("texconv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tinyxml2 {
            get {
                object obj = ResourceManager.GetObject("tinyxml2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] towav {
            get {
                object obj = ResourceManager.GetObject("towav", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] unlub {
            get {
                object obj = ResourceManager.GetObject("unlub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] unpack {
            get {
                object obj = ResourceManager.GetObject("unpack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon wavIcon {
            get {
                object obj = ResourceManager.GetObject("wavIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wavLogo {
            get {
                object obj = ResourceManager.GetObject("wavLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xextool {
            get {
                object obj = ResourceManager.GetObject("xextool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 584D4132240000000301000000000000000000000000BB8000FF000000004C00000048B600000001010000017365656B0400000000004C00.
        /// </summary>
        internal static string xma_Patch {
            get {
                return ResourceManager.GetString("xma_Patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xmaBG {
            get {
                object obj = ResourceManager.GetObject("xmaBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xmaencode2008 {
            get {
                object obj = ResourceManager.GetObject("xmaencode2008", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon xmaIcon {
            get {
                object obj = ResourceManager.GetObject("xmaIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xmaLogo {
            get {
                object obj = ResourceManager.GetObject("xmaLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000000100000000.
        /// </summary>
        internal static string xno_Cull {
            get {
                return ResourceManager.GetString("xno_Cull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3600000100000000.
        /// </summary>
        internal static string xno_Decull {
            get {
                return ResourceManager.GetString("xno_Decull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xno2dae {
            get {
                object obj = ResourceManager.GetObject("xno2dae", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
